### ISSUE TITLE
Adding tests to xkcd-dl

### ISSUE THREAD

**Issue by eternalfool** [tasdikrahman/xkcd-dl#39]
Here is my test plan.
> All tests would run in /tmp/xkcd-dl-home/
> update_dict() creates new dict in specified xkcd_dict_location. Check if file is created and size > 0
> test_download_one() --> Would download a jpeg, png and gif xkcd comic and test if specified folders are created with the images and description.
> test_show_xkcd -> show xkcd comic not downloaded. show xkcd comic already downloaded.
> Should this actually open a comic?
> test_download_range() - download a certain range and check if folders are created
> I did not get set_custom_path to work. What is it’s intended behaviour?
> test_download_latest() <— I think this might be a little redundant.

So do tell me if I’m missing some obvious things/or something else completely.

**Comment by prodicus** [comment]
Hey @eternalfool 

I would suggest you also take a look at the work which was done by @BlitzKraft on #32 

You can continue from there

**Comment by prodicus** [comment]
I am thinking of getting the functional tests first, and then the whole integration tests. Take a look at python mocks too as we would be depending on the xkcd JSON API.

**Comment by prodicus** [comment]
For reference, you can have a look at how we wrote tests for [vocabulary](https://github.com/prodicus/vocabulary/blob/master/tests/tests.py). Might give you a head start. 
Let me know if you have anything in mind. 

Cheers!

**Comment by tasdikrahman** [comment]
closed by https://github.com/tasdikrahman/xkcd-dl/pull/43
